# 应用程序配置
spring:
  # 应用名称
  application:
    name: ContractManager

  # 数据库配置
  datasource:
    # 使用阿里巴巴Druid作为连接池
    type: com.alibaba.druid.pool.DruidDataSource
    # MySQL JDBC驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接URL
    url: jdbc:mysql://localhost:3306/contract_manager
    # 数据库用户名
    username: root
    # 数据库密码
    password: root

# MyBatis Plus配置
mybatis-plus:
  # 全局配置
  global-config:
    # 数据库配置
    db-config:
      # 主键自增策略
      id-type: auto
  # 配置设置
  configuration:
    # 启用SQL日志输出
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启下划线到驼峰命名的自动转换
    map-underscore-to-camel-case: true
  type-aliases-package: com.ktriasia.contractmanager.model.pojo